export const labData = [
    { type: 'low wage', number: 101 }
    , { type: 'low wage', number: 102 }
    , { type: 'low wage', number: 103 }
    , { type: 'low wage', number: 104 }
    , { type: 'High wage', number: 105 }
    , { type: 'low wage', number: 106 }
    , { type: 'low wage', number: 107 }
    , { type: 'low wage', number: 108 }
    , { type: 'low wage', number: 109 }
    , { type: 'low wage', number: 110 }
    , { type: 'low wage', number: 111 }
    , { type: 'High wage', number: 112 }
    , { type: 'High wage', number: 113 }
    , { type: 'low wage', number: 114 }
    , { type: 'High wage', number: 115 }
    , { type: 'low wage', number: 116 }
    , { type: 'High wage', number: 117 }
    , { type: 'low wage', number: 118 }
    , { type: 'low wage', number: 119 }
    , { type: 'low wage', number: 120 }
    , { type: 'High wage', number: 121 }
    , { type: 'High wage', number: 122 }
    , { type: 'low wage', number: 123 }
    , { type: 'low wage', number: 124 }
    , { type: 'High wage', number: 125 }
    , { type: 'low wage', number: 126 }
    , { type: 'low wage', number: 127 }
    , { type: 'High wage', number: 128 }
    , { type: 'High wage', number: 129 }
    , { type: 'High wage', number: 130 }
    , { type: 'low wage', number: 131 }
    , { type: 'low wage', number: 132 }
    , { type: 'low wage', number: 133 }
    , { type: 'low wage', number: 134 }
    , { type: 'High wage', number: 135 }
    , { type: 'low wage', number: 136 }
    , { type: 'low wage', number: 137 }
    , { type: 'low wage', number: 138 }
    , { type: 'low wage', number: 139 }
    , { type: 'low wage', number: 140 }
    , { type: 'low wage', number: 141 }
    , { type: 'High wage', number: 142 }
    , { type: 'High wage', number: 143 }
    , { type: 'High wage', number: 144 }
    , { type: 'High wage', number: 145 }
    , { type: 'low wage', number: 146 }
    , { type: 'low wage', number: 147 }
    , { type: 'High wage', number: 148 }
    , { type: 'High wage', number: 149 }
    , { type: 'low wage', number: 150 }
    , { type: 'low wage', number: 151 }
    , { type: 'low wage', number: 152 }
    , { type: 'low wage', number: 153 }
    , { type: 'low wage', number: 154 }
    , { type: 'low wage', number: 155 }
    , { type: 'low wage', number: 156 }
    , { type: 'High wage', number: 157 }
    , { type: 'low wage', number: 158 }
    , { type: 'low wage', number: 159 }
    , { type: 'low wage', number: 160 }
    , { type: 'low wage', number: 161 }
    , { type: 'High wage', number: 162 }
    , { type: 'High wage', number: 163 }
    , { type: 'High wage', number: 164 }
    , { type: 'low wage', number: 165 }
    , { type: 'low wage', number: 167 }
    , { type: 'low wage', number: 168 }
    , { type: 'High wage', number: 169 }
    , { type: 'low wage', number: 170 }
    , { type: 'High wage', number: 171 }
    , { type: 'low wage', number: 172 }
    , { type: 'High wage', number: 173 }
    , { type: 'low wage', number: 174 }
    , { type: 'low wage', number: 175 }
    , { type: 'low wage', number: 176 }
    , { type: 'low wage', number: 177 }
    , { type: 'High wage', number: 178 }
    , { type: 'High wage', number: 179 }
    , { type: 'High wage', number: 180 }
    , { type: 'High wage', number: 181 }
    , { type: 'low wage', number: 182 }
    , { type: 'High wage', number: 183 }
    , { type: 'High wage', number: 184 }
    , { type: 'low wage', number: 185 }
    , { type: 'low wage', number: 186 }
    , { type: 'low wage', number: 187 }
    , { type: 'low wage', number: 188 }
    , { type: 'low wage', number: 189 }
    , { type: 'High wage', number: 190 }
    , { type: 'low wage', number: 191 }
    , { type: 'low wage', number: 192 }
    , { type: 'low wage', number: 193 }
    , { type: 'low wage', number: 194 }
    , { type: 'low wage', number: 195 }
    , { type: 'low wage', number: 196 }
];